SELECT [SAManager].[dbo].[PACK].[PACKID]
      ,[SAManager].[dbo].[PACK].[ARTID]
      ,[SAManager].[dbo].[EXBARC].[EXBARCBODY]
      ,[SAManager].[dbo].[PACKPRC].[PACKPRICE]
      ,[SAManager].[dbo].[PACKPRC].[PRCLEVELID]
      ,[SAManager].[dbo].[PRCLEVEL].[PRCLEVELNAME]
      ,[SAManager].[dbo].[PACK].[PACKNAME]
      ,[SAManager].[dbo].[ART].[ARTNAME]
      ,[SAManager].[dbo].[PACK].[OFFERID]
      ,[SAManager].[dbo].[OFFER].[OFFERNAME]
      ,[SAManager].[dbo].[PACK].[PROPERTYGRPID]      
      ,[SAManager].[dbo].[PACK].[PACKQUANT]
      ,[SAManager].[dbo].[PACK].[DELFLAG]
      ,[SAManager].[dbo].[PACK].[UPDATENUM]
      
  FROM [SAManager].[dbo].[PACK] 
  JOIN [SAManager].[dbo].[EXBARC]
  ON [SAManager].[dbo].[PACK].[PACKID] = [SAManager].[dbo].[EXBARC].[PACKID]
  JOIN [SAManager].[dbo].[PACKPRC]
  ON [SAManager].[dbo].[PACK].[PACKID] = [SAManager].[dbo].[PACKPRC].[PACKID]
  JOIN [SAManager].[dbo].[PRCLEVEL]
  ON [SAManager].[dbo].[PACKPRC].[PRCLEVELID] = [SAManager].[dbo].[PRCLEVEL].[PRCLEVELID]
  JOIN[SAManager].[dbo].[ART]
  ON [SAManager].[dbo].[PACK].[ARTID] = [SAManager].[dbo].[ART].[ARTID]
  LEFT JOIN [SAManager].[dbo].[OFFER]
  ON [SAManager].[dbo].[PACK].[OFFERID] = [SAManager].[dbo].[OFFER].[OFFERID]  
  ORDER BY [SAManager].[dbo].[PACK].[PACKNAME]
  